### ISSUE TITLE
Assertion failure when attempting to use symbolic links on Windows with git-bash and submodules

### ISSUE THREAD

**Issue by Klaim** [build2/build2#97]
Context
---------

I initially found this issue while working with `v0.13.0` but I can also see it with the current stage:

```
$ b --version
build2 0.13.0
libbutl 0.13.0
host x86_64-microsoft-win32-msvc14.2
Copyright (c) 2014-2020 the build2 authors.
This is free software released under the MIT license.
```

```
$ b --version
build2 0.14.0-a.0.d7571f706928
libbutl 0.14.0-a.0.4c937646225f
host x86_64-microsoft-win32-msvc14.2
Copyright (c) 2014-2020 the build2 authors.
This is free software released under the MIT license.
```

I also reinstalled/upgraded git/git-bash to be sure it wasn't related to something there: 
```
$ git --version
git version 2.28.0.windows.1
```
And my git-bash is setup so that it is based on `cmd` instead of `cygwin`. It have symbolic link support enabled (in the installer).

Only on Windows 10, the repro-case works perfectly on Linux.

I didn't have time to explore the issue more though, or try on another computer/setup.

How To Reproduce
---------------------

0. On Windows 10  in a git-bash window, make sure you have setup git so that symlinks are enabled (the appropriate `git config [--system/local/global] core.symlink` must be `true`).
1. `git clone git@github.com:Klaim/build2-range-v3.git range-v3 && cd range-v3`
    - **Note: update - switch to the `bug/symlinks` branch** : `git switch bug/symlinks`
2. `git submodule init && git submodule update` (the `upstream` symlinks in `test/`, `perf/` and `example/` will point to directories in the submodule set at `upstream/*`.
3. `bdep init -C ../build-msvc/ @msvc cc config.cxx=cl config.c=cl`

Observed
----------

```
$ bdep init -C ../build-msvc @msvc cc config.cxx=cl config.c=cl
initializing in project C:\Users\klaim\temp\range-v3-build2\range-v3\
created configuration @msvc C:\Users\klaim\temp\range-v3-build2\build-msvc\ 1 default,forwarded,auto-synchronized
synchronizing:
  new range-v3/0.11.0-a.0.20200820192660
Assertion failed: e.code ().category () == generic_category (), file E:\tools\build2\build2-toolchain-0.13\libbutl-0.13.0\libbutl\filesystem.cxx, line 2574
error: process b terminated abnormally: aborted
```

Complete log of my attempts:

```
klaim@KLAIMDEV MINGW64 ~/temp
$ mkdir range-v3-build2

klaim@KLAIMDEV MINGW64 ~/temp
$ cd range-v3-build2/

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2
$ git clone git@github.com:Klaim/build2-range-v3.git range-v3
Cloning into 'range-v3'...
remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 51 (delta 17), reused 49 (delta 15), pack-reused 0
Receiving objects: 100% (51/51), 8.80 KiB | 1.26 MiB/s, done.
Resolving deltas: 100% (17/17), done.

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2
$ git config --system core.symlinks
true

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2
$ git config --global core.symlinks
true

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2
$ cd range-v3

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2/range-v3 (master)
$ git config --local core.symlinks

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2/range-v3 (master)
$ explorer .

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2/range-v3 (master)
$ git submodule init
Submodule 'upstream' (https://github.com/ericniebler/range-v3.git) registered for path 'upstream'

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2/range-v3 (master)
$ git submodule update
Cloning into 'C:/Users/klaim/temp/range-v3-build2/range-v3/upstream'...
Submodule path 'upstream': checked out '4989f3e9ff2efee1852942bb9328ef121369ba02'

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2/range-v3 (master)
$ bdep init -C ../build-msvc @msvc cc config.cxx=cl config.c=cl
initializing in project C:\Users\klaim\temp\range-v3-build2\range-v3\
created configuration @msvc C:\Users\klaim\temp\range-v3-build2\build-msvc\ 1 default,forwarded,auto-synchronized
synchronizing:
  new range-v3/0.11.0-a.0.20200820192660
Assertion failed: e.code ().category () == generic_category (), file E:\tools\build2\build2-toolchain-0.13\libbutl-0.13.0\libbutl\filesystem.cxx, line 2574
error: process b terminated abnormally: aborted

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2/range-v3 (master)
$ b --version
build2 0.13.0
libbutl 0.13.0
host x86_64-microsoft-win32-msvc14.2
Copyright (c) 2014-2020 the build2 authors.
This is free software released under the MIT license.

#
# At this point,
# In another window, I updated my build2 stage install and switch to that build2 version
#

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2/range-v3 (master)
$ bdep init
initializing in project C:\Users\klaim\temp\range-v3-build2\range-v3\
synchronizing:
  downgrade range-v3/0.11.0-a.0.20200820192659.3b017255e445
Assertion failed: e.code ().category () == generic_category (), file E:\tools\build2\build2-toolchain-0.14-a.0\libbutl-0.14.0-a.0.20200806141938.4c937646225f\libbutl\filesystem.cxx, line 2576
error: process b terminated abnormally: aborted

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2/range-v3 (master)
$ b --version
build2 0.14.0-a.0.d7571f706928
libbutl 0.14.0-a.0.4c937646225f
host x86_64-microsoft-win32-msvc14.2
Copyright (c) 2014-2020 the build2 authors.
This is free software released under the MIT license.

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2/range-v3 (master)
$ ls test/
build2/  build2file  upstream@

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2/range-v3 (master)
$ ls example/
build2/  build2file  upstream@

klaim@KLAIMDEV MINGW64 ~/temp/range-v3-build2/range-v3 (master)
$ ls perf/
build2/  build2file  upstream@

```

**Comment by karen-arutyunov** [comment]
Thanks for the report.

The assertion failure should be fixed in the latest staged version of the toolchain.

Note, however, that now bdep-init ends up with the following error (or similar):

test\build2file:6:32: error: unable to scan test\upstream/: access is denied

The problem is that git-clone creates the test\upstream symlink of a file type rather than of a directory type since it has no information about the target type at the time of the symlink creation. On Windows such a mismatch makes symlinks unusable.

Thus, if the project is supposed to be developed on Windows the symlink=dir attribute needs to be specified for directory symlinks in the .gitattributes file (see https://github.com/git-for-windows/git/commit/be24ffe3d9a24c4a49a42c74665fb47c431b3c12 commit for details).

**Comment by Klaim** [comment]
Thanks @karen-arutyunov 

> The assertion failure should be fixed in the latest staged version of the toolchain.

I can confirm that the issue seems fixe with:
```
$ b --version
build2 0.14.0-a.0.714142573cf1
libbutl 0.14.0-a.0.ab080add2681
host x86_64-microsoft-win32-msvc14.2
```

> Note, however, that now bdep-init ends up with the following error (or similar):
> 
> test\build2file:6:32: error: unable to scan test\upstream/: access is denied
> 
> The problem is that git-clone creates the test\upstream symlink of a file type rather than of a directory type since it has no information about the target type at the time of the symlink creation. On Windows such a mismatch makes symlinks unusable.
> 
> Thus, if the project is supposed to be developed on Windows the symlink=dir attribute needs to be specified for directory symlinks in the .gitattributes file (see [git-for-windows/git@be24ffe](https://github.com/git-for-windows/git/commit/be24ffe3d9a24c4a49a42c74665fb47c431b3c12) commit for details).

This works, though I believe the git developers actually broke the previous behavior which was apparently deducing correctly the link type (maybe because it was done at a different time than currently). I still have the git clone I made before upgrading git to that version, and it correctly deduced symlinks to directories. So I just cleaned and built with `build2` stage version and it worked without adding attributes. But making a fresh clone of that repo does trigger the error you're pointing.

Anyway, although the project is a packaging of a project under CMake, I still need it to work on all platforms, so I added the attributes in that branch to check and it does work as expected.

Thanks!

**Comment by boris-kolpackov** [comment]
I've added a note about this in https://build2.org/article/symlinks.xhtml#windows
